name: Deploying A Container

on:
    push:
        branches:
            - main
            - dev

jobs:
    deploy:
        environment: deployment
        container:
            image: python:3.10
        runs-on: ubuntu-latest
        services:
            mysql: 
                image: mysql
                env:
                    MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
                    MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        steps:
            - name: Get Code
              uses: actions/checkout@v4