name: Deploying A Container

on:
    push:
        branches:
            - main
            - dev

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4