name: Deploying A Container

on:
    push:
        branches:
            - main
            - dev

jobs:
    deploy:
        environment: deployment
        container:
            image: python:3.10
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4